/**
 * Daksha catalogue presets for the Quote Builder.
 *
 * The picker is deliberately family-first and plain-language. Operators pick a familiar
 * product line, then start from one common construction and edit only what differs.
 */
import type { CableFamily, CableSpec } from "@/lib/services/types";

export interface CableFamilyMeta {
  family: CableFamily;
  displayName: string;
  plainHint: string;
  typicalUse: string;
}

export interface CablePreset {
  id: string;
  family: CableFamily;
  displayName: string;
  description?: string;
  tags?: string[];
  typicalUse?: string;
  spec: Omit<CableSpec, "id" | "designation" | "cableCode">;
  defaultMarginPct?: number;
  defaultOverheadPerM?: number;
  defaultLengthM?: number;
}

export const cableFamilies: CableFamilyMeta[] = [
  {
    family: "LT XLPE Power",
    displayName: "LT XLPE power",
    plainHint: "Main power feeder cables for factories, buildings, and infrastructure.",
    typicalUse: "Power distribution feeders",
  },
  {
    family: "LT PVC Power",
    displayName: "LT PVC power",
    plainHint: "Cost-effective 1.1 kV PVC power cables for indoor and outdoor runs.",
    typicalUse: "Street lighting, sub-feeders, industrial wiring",
  },
  {
    family: "Control Cable",
    displayName: "Control cable",
    plainHint: "Multi-core copper cables for control panels, stations, and signalling.",
    typicalUse: "Control and measuring circuits",
  },
  {
    family: "FR/FRLS/ZHFR Cable",
    displayName: "Fire-safe cable",
    plainHint: "FR, FRLS, and zero-halogen cable where fire safety matters.",
    typicalUse: "Plants, buildings, public infrastructure",
  },
  {
    family: "House Wiring",
    displayName: "House wiring",
    plainHint: "Flexible copper wire for building and panel wiring.",
    typicalUse: "Homes, panels, lighting circuits",
  },
  {
    family: "Weatherproof Cable",
    displayName: "Weatherproof cable",
    plainHint: "Outdoor PVC cable for exposed runs and service connections.",
    typicalUse: "Outdoor wiring and temporary supply",
  },
  {
    family: "Screened Instrumentation",
    displayName: "Instrumentation cable",
    plainHint: "Screened pair or triad cables for signals and measurement.",
    typicalUse: "Instrumentation and process control",
  },
  {
    family: "Thermocouple Cable",
    displayName: "Thermocouple cable",
    plainHint: "Extension cable for temperature sensing circuits.",
    typicalUse: "Temperature measurement",
  },
  {
    family: "Aerial Bunched Cable",
    displayName: "Aerial bunched cable",
    plainHint: "Overhead bunched supply cable with messenger support.",
    typicalUse: "Utility distribution to consumers",
  },
  {
    family: "Submersible Cable",
    displayName: "Submersible cable",
    plainHint: "Water-resistant cable for pump motors.",
    typicalUse: "Borewell and pump sets",
  },
  {
    family: "Solar DC Cable",
    displayName: "Solar DC cable",
    plainHint: "UV-resistant DC cable for photovoltaic systems.",
    typicalUse: "Solar strings and DC runs",
  },
  {
    family: "Covered Conductor",
    displayName: "Covered conductor",
    plainHint: "Overhead covered conductor for safer MV distribution.",
    typicalUse: "Forest, crossing, and right-of-way constrained lines",
  },
];

export const cablePresets: CablePreset[] = [
  {
    id: "PRESET-LT-XLPE-AL-240-35C",
    family: "LT XLPE Power",
    displayName: "Aluminium XLPE armoured 240 - 3.5 core",
    description: "Common LT feeder. XLPE insulation, strip armoured, FRLS sheath.",
    tags: ["feeder", "armoured", "FRLS"],
    defaultMarginPct: 14,
    defaultOverheadPerM: 820,
    defaultLengthM: 1000,
    spec: {
      family: "LT XLPE Power",
      standard: "IS 7098-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3.5C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 240,
      neutralSizeSqMm: 120,
      insulation: "XLPE",
      armour: "GI strip (GSS)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      technical: { approxCurrentRatingInGroundA: 392, coreIdentification: "R-Y-B with reduced neutral" },
    },
  },
  {
    id: "PRESET-LT-XLPE-AL-95-4C",
    family: "LT XLPE Power",
    displayName: "Aluminium XLPE armoured 95 - 4 core",
    description: "Mid-size distribution cable with round-wire armour.",
    tags: ["distribution", "armoured"],
    defaultMarginPct: 15,
    defaultOverheadPerM: 360,
    defaultLengthM: 1000,
    spec: {
      family: "LT XLPE Power",
      standard: "IS 7098-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "4C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 95,
      insulation: "XLPE",
      armour: "GI round wire (GSW)",
      sheath: "FR PVC",
      flameClass: "FR",
    },
  },
  {
    id: "PRESET-LT-PVC-AL-50-4C",
    family: "LT PVC Power",
    displayName: "Aluminium PVC armoured 50 - 4 core",
    description: "Cost-effective LT PVC cable for sub-feeders and street lighting.",
    tags: ["PVC", "street lighting"],
    defaultMarginPct: 16,
    defaultOverheadPerM: 220,
    defaultLengthM: 1000,
    spec: {
      family: "LT PVC Power",
      standard: "IS 1554-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "4C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 50,
      insulation: "PVC (Type A)",
      armour: "GI round wire (GSW)",
      sheath: "PVC (ST1)",
      flameClass: "Standard",
    },
  },
  {
    id: "PRESET-CONTROL-CU-25-12C",
    family: "Control Cable",
    displayName: "Copper control 2.5 - 12 core",
    description: "GI wire armoured control cable for panels, stations, and signalling.",
    tags: ["control", "signalling", "copper"],
    defaultMarginPct: 18,
    defaultOverheadPerM: 85,
    defaultLengthM: 500,
    spec: {
      family: "Control Cable",
      standard: "IS 1554-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "12C",
      conductorMaterial: "Copper",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 2.5,
      insulation: "PVC (Type A)",
      armour: "GI round wire (GSW)",
      sheath: "PVC (ST1)",
      flameClass: "Standard",
      technical: { coreIdentification: "Numbered or colour coded cores" },
    },
  },
  {
    id: "PRESET-FRLS-CU-16-3C",
    family: "FR/FRLS/ZHFR Cable",
    displayName: "Copper FRLS flexible 16 - 3 core",
    description: "Fire-retardant low-smoke cable for safer installations.",
    tags: ["FRLS", "flexible", "fire safety"],
    defaultMarginPct: 18,
    defaultOverheadPerM: 140,
    defaultLengthM: 500,
    spec: {
      family: "FR/FRLS/ZHFR Cable",
      standard: "IS 694",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3C",
      conductorMaterial: "Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 16,
      insulation: "PVC (Type A)",
      armour: "Unarmoured",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
    },
  },
  {
    id: "PRESET-HOUSE-CU-25-1C",
    family: "House Wiring",
    displayName: "Copper house wire 2.5 - single core",
    description: "Flexible PVC insulated wire for building and panel circuits.",
    tags: ["house wiring", "flexible"],
    defaultMarginPct: 20,
    defaultOverheadPerM: 22,
    defaultLengthM: 900,
    spec: {
      family: "House Wiring",
      standard: "IS 694",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "1C",
      conductorMaterial: "Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 2.5,
      insulation: "PVC (Type A)",
      armour: "Unarmoured",
      sheath: "PVC (ST1)",
      flameClass: "FR",
      technical: { colour: "Red / Yellow / Blue / Black / Green" },
    },
  },
  {
    id: "PRESET-WEATHERPROOF-AL-16-2C",
    family: "Weatherproof Cable",
    displayName: "Aluminium weatherproof 16 - 2 core",
    description: "Outdoor service cable with weatherproof PVC covering.",
    tags: ["outdoor", "service"],
    defaultMarginPct: 17,
    defaultOverheadPerM: 65,
    defaultLengthM: 500,
    spec: {
      family: "Weatherproof Cable",
      standard: "IS 694",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "2C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 16,
      insulation: "PVC (Type A)",
      armour: "Unarmoured",
      sheath: "Weatherproof PVC",
      flameClass: "Standard",
    },
  },
  {
    id: "PRESET-INST-CU-15-8P",
    family: "Screened Instrumentation",
    displayName: "Instrumentation 1.5 - 8 pair screened",
    description: "Screened pair cable for signal and measurement circuits.",
    tags: ["screened", "pairs", "signals"],
    defaultMarginPct: 19,
    defaultOverheadPerM: 95,
    defaultLengthM: 1000,
    spec: {
      family: "Screened Instrumentation",
      standard: "BS EN 60228",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "1C",
      conductorMaterial: "Copper",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 1.5,
      insulation: "PVC (Type A)",
      armour: "GI round wire (GSW)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      screened: true,
      instrumentation: {
        grouping: "Pair",
        groupCount: 8,
        individualScreen: true,
        overallScreen: true,
        drainWire: true,
      },
    },
  },
  {
    id: "PRESET-THERMO-K-1P",
    family: "Thermocouple Cable",
    displayName: "Thermocouple type K - 1 pair",
    description: "Extension cable for temperature sensing.",
    tags: ["temperature", "type K"],
    defaultMarginPct: 22,
    defaultOverheadPerM: 70,
    defaultLengthM: 300,
    spec: {
      family: "Thermocouple Cable",
      standard: "IEC 60584",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "2C",
      conductorMaterial: "Thermocouple Alloy",
      conductorClass: "Thermocouple extension",
      conductorSizeSqMm: 1.5,
      insulation: "PVC (Type C)",
      armour: "Unarmoured",
      sheath: "FR PVC",
      flameClass: "FR",
      thermocouple: { thermocoupleType: "K", pairCount: 1, extensionGrade: true },
    },
  },
  {
    id: "PRESET-ABC-3P-70",
    family: "Aerial Bunched Cable",
    displayName: "ABC 3 phase 70 with messenger",
    description: "Overhead bunched cable with aluminium alloy messenger.",
    tags: ["overhead", "messenger", "utility"],
    defaultMarginPct: 16,
    defaultOverheadPerM: 310,
    defaultLengthM: 1000,
    spec: {
      family: "Aerial Bunched Cable",
      standard: "IS 14255",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 70,
      insulation: "XLPE",
      armour: "Unarmoured",
      sheath: "HDPE",
      flameClass: "Standard",
      aerialBunched: {
        phaseCount: 3,
        phaseSizeSqMm: 70,
        messengerSizeSqMm: 50,
        messengerInsulated: false,
        streetLightSizeSqMm: 16,
      },
      technical: { colour: "Black with phase ridges" },
    },
  },
  {
    id: "PRESET-SUBMERSIBLE-CU-4-3C",
    family: "Submersible Cable",
    displayName: "Submersible copper 4 - 3 core flat",
    description: "Water-resistant flat cable for pump motors.",
    tags: ["pump", "flat", "water resistant"],
    defaultMarginPct: 18,
    defaultOverheadPerM: 58,
    defaultLengthM: 500,
    spec: {
      family: "Submersible Cable",
      standard: "IS 9968-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3C",
      conductorMaterial: "Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 4,
      insulation: "PVC (Type A)",
      armour: "Unarmoured",
      sheath: "PVC (ST1)",
      flameClass: "Standard",
      submersible: { shape: "Flat", waterResistant: true },
    },
  },
  {
    id: "PRESET-SOLAR-DC-6-1C",
    family: "Solar DC Cable",
    displayName: "Solar DC 6 - single core",
    description: "UV-resistant, halogen-free DC string cable.",
    tags: ["solar", "UV", "LSZH"],
    defaultMarginPct: 20,
    defaultOverheadPerM: 60,
    defaultLengthM: 2000,
    spec: {
      family: "Solar DC Cable",
      standard: "EN 50618",
      voltageGrade: "600/1000 V DC",
      cores: "1C",
      conductorMaterial: "Tinned Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 6,
      insulation: "XLPO (solar/UV)",
      armour: "Unarmoured",
      sheath: "Zero-halogen (ZHFR/LSZH)",
      flameClass: "LSZH",
      solar: { dcPolarityColour: "Black", halogenFree: true, uvResistant: true },
    },
  },
  {
    id: "PRESET-COVERED-AAAC-70-11KV",
    family: "Covered Conductor",
    displayName: "Covered conductor AAAC 70 - 11 kV",
    description: "Anti-tracking covered conductor for safer overhead lines.",
    tags: ["MV", "anti-tracking", "overhead"],
    defaultMarginPct: 17,
    defaultOverheadPerM: 260,
    defaultLengthM: 1000,
    spec: {
      family: "Covered Conductor",
      standard: "SS EN 50397-1",
      voltageGrade: "6.35/11 kV",
      cores: "1C",
      conductorMaterial: "AAAC",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 70,
      insulation: "XLPE anti-tracking",
      armour: "Unarmoured",
      sheath: "HDPE",
      flameClass: "Standard",
      coveredConductor: {
        networkVoltageKv: "13.8",
        conductorConstruction: "AAAC",
        waterTight: true,
        antiTrackingOuter: true,
      },
    },
  },
];
