import type { CableStore } from "@/lib/services/types";

export const seedData: CableStore = {
  org: {
    companyName: "Autoloom Cables Pvt. Ltd.",
    gstin: "27AAHCA2600A1ZV",
    homeStateCode: "27",
    address: "MIDC Industrial Area, Pune, Maharashtra",
    timezone: "Asia/Kolkata",
  },
  policies: {
    // Off for the PoC — don't gate quotes on a rule the client hasn't validated yet.
    marginGateEnabled: false,
    marginThresholdPct: 12,
    ewayThresholdInr: 50000,
    gstRatePct: 18,
    creditLimitEnforced: true,
    dispatchHoldMode: "soft",
  },
  users: [
    { id: "USR-001", name: "Asha Owner", email: "owner@autoloom.test", role: "Owner", active: true },
    { id: "USR-002", name: "Ravi Sales", email: "sales@autoloom.test", role: "Sales", active: true },
    { id: "USR-003", name: "Meera Ops", email: "ops@autoloom.test", role: "Operations", active: true },
    { id: "USR-004", name: "Kabir Accounts", email: "accounts@autoloom.test", role: "Accounts", active: true },
  ],
  materials: [
    // Conductors — auto-refreshed from the MCX metal index.
    { id: "MAT-AL", name: "Aluminium (EC grade)", category: "Conductor", ratePerKg: 248, source: "MCX", matchMaterial: "Aluminium", updatedAt: "2026-06-23T08:30:00+05:30" },
    { id: "MAT-CU", name: "Copper (ETP grade)", category: "Conductor", ratePerKg: 886, source: "MCX", matchMaterial: "Copper", updatedAt: "2026-06-23T08:30:00+05:30" },
    // Insulation compounds — manual.
    { id: "MAT-XLPE", name: "XLPE compound", category: "Insulation", ratePerKg: 165, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-PVC-INS", name: "PVC insulation compound", category: "Insulation", ratePerKg: 120, source: "Manual", updatedAt: "2026-06-20" },
    // Armour — manual.
    { id: "MAT-GI", name: "GI strip / wire (armour)", category: "Armour", ratePerKg: 95, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-AL-ARMOUR", name: "Aluminium armour wire", category: "Armour", ratePerKg: 252, source: "Manual", updatedAt: "2026-06-20" },
    // Sheath — manual.
    { id: "MAT-PVC-SH", name: "PVC sheath compound", category: "Sheath", ratePerKg: 110, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-LSZH", name: "Zero-halogen (LSZH) sheath", category: "Sheath", ratePerKg: 240, source: "Manual", updatedAt: "2026-06-20" },
  ],
  specs: [
    {
      id: "SPEC-240-35C",
      family: "LT XLPE Power",
      standard: "IS 7098-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3.5C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 240,
      neutralSizeSqMm: 120,
      insulation: "XLPE",
      armour: "GI strip (GSS)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      designation: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS, 1.1kV",
      cableCode: "A2XFY",
      approxOuterDiaMm: 58,
      approxWeightKgPerKm: 3520,
      bisLicenceNo: "CM/L-7200123456",
      rohsCompliant: true,
    },
    {
      id: "SPEC-185-4C",
      standard: "IS 1554-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "4C",
      conductorMaterial: "Copper",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 185,
      insulation: "PVC (Type C)",
      armour: "GI round wire (GSW)",
      sheath: "PVC (ST2)",
      flameClass: "FR",
      designation: "4C x 185 sq mm Cu, HR PVC, GI round wire armoured, 1.1kV",
      cableCode: "YWY",
      approxOuterDiaMm: 54,
      approxWeightKgPerKm: 6920,
      rohsCompliant: true,
    },
    {
      id: "SPEC-11KV-1C",
      standard: "IS 7098-2",
      voltageGrade: "6.35/11 kV",
      cores: "1C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 300,
      insulation: "XLPE",
      armour: "Aluminium wire (AWA)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      screened: true,
      designation: "1C x 300 sq mm Al, screened XLPE, AWA armoured, FRLS, 11kV",
      cableCode: "A2XWAY",
      approxOuterDiaMm: 44,
      approxWeightKgPerKm: 2480,
      bisLicenceNo: "CM/L-7200456789",
      rohsCompliant: true,
    },
    {
      id: "SPEC-SOLAR-16",
      standard: "IEC 60502-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "1C",
      conductorMaterial: "Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 16,
      insulation: "XLPO (solar/UV)",
      armour: "Unarmoured",
      sheath: "Zero-halogen (ZHFR/LSZH)",
      flameClass: "LSZH",
      designation: "1C x 16 sq mm Cu flexible solar DC cable, XLPO, LSZH",
      cableCode: "PV1-F",
      approxOuterDiaMm: 9,
      approxWeightKgPerKm: 190,
      rohsCompliant: true,
    },
  ],
  customers: [
    {
      id: "CUS-101",
      name: "Shakti Infra Projects",
      segment: "EPC contractor",
      contactName: "Nitin Rao",
      phone: "+91 98765 11001",
      email: "procurement@shaktiinfra.test",
      billingAddress: "Andheri East, Mumbai",
      shippingAddress: "Metro Package 4, Thane",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400069",
      gstin: "27AABCS1234F1Z5",
      stateCode: "27",
      paymentTerms: "30 days from invoice",
      creditLimitInr: 12000000,
      creditUsedInr: 7800000,
      crmId: "CRM-001",
      createdAt: "2026-06-01",
    },
    {
      id: "CUS-102",
      name: "Dakshin Solar EPC",
      segment: "Solar installer",
      contactName: "Priya Menon",
      phone: "+91 98765 11002",
      email: "buy@dakshinsolar.test",
      billingAddress: "Peenya Industrial Area, Bengaluru",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560058",
      gstin: "29AAECD4567H1ZX",
      stateCode: "29",
      paymentTerms: "50% advance, balance before dispatch",
      creditLimitInr: 4500000,
      creditUsedInr: 4200000,
      msmeRegistered: true,
      crmId: "CRM-002",
      createdAt: "2026-06-03",
    },
    {
      id: "CUS-103",
      name: "Narmada Utilities Board",
      segment: "Government/PSU",
      contactName: "Arvind Shah",
      phone: "+91 98765 11003",
      email: "tender@narmadautilities.test",
      billingAddress: "Race Course Road, Vadodara",
      city: "Vadodara",
      state: "Gujarat",
      pincode: "390007",
      gstin: "24AAALN9999C1Z8",
      stateCode: "24",
      paymentTerms: "45 days, BG required",
      creditLimitInr: 22000000,
      creditUsedInr: 3000000,
      createdAt: "2026-06-05",
    },
    {
      id: "CUS-104",
      name: "Vector OEM Drives",
      segment: "OEM",
      contactName: "Farah Khan",
      phone: "+91 98765 11004",
      email: "purchase@vectoroem.test",
      billingAddress: "Chakan MIDC, Pune",
      city: "Pune",
      state: "Maharashtra",
      pincode: "410501",
      gstin: "27AAACV8080D1ZM",
      stateCode: "27",
      paymentTerms: "15 days from invoice",
      creditLimitInr: 3000000,
      creditUsedInr: 900000,
      createdAt: "2026-06-08",
    },
  ],
  inquiries: [
    {
      id: "INQ-2606-041",
      customerId: "CUS-101",
      requirement: "Metro feeder cable for package 4",
      specIds: ["SPEC-240-35C", "SPEC-11KV-1C", "SPEC-SOLAR-16"],
      commercialTerms: "Delivery split and payment terms to be confirmed with customer.",
      source: "Repeat order",
      estimatedValueInr: 8650000,
      stage: "Quote sent",
      ownerRole: "Sales",
      nextAction: "Confirm final delivery split",
      followUpDate: "2026-06-23",
      createdAt: "2026-06-12",
    },
    {
      id: "INQ-2606-042",
      customerId: "CUS-103",
      requirement: "11kV screened cable tender",
      specIds: ["SPEC-11KV-1C"],
      source: "Tender portal",
      tenderRef: "NUB/11KV/2026/118",
      estimatedValueInr: 14800000,
      stage: "Quoting",
      ownerRole: "Sales",
      nextAction: "Owner approval for EMD and margin",
      followUpDate: "2026-06-24",
      createdAt: "2026-06-15",
    },
    {
      id: "INQ-2606-043",
      customerId: "CUS-102",
      requirement: "Solar DC cable for 12 MW site",
      specIds: ["SPEC-SOLAR-16"],
      source: "Website",
      estimatedValueInr: 2850000,
      stage: "New",
      ownerRole: "Sales",
      nextAction: "Capture drum schedule",
      followUpDate: "2026-06-25",
      createdAt: "2026-06-20",
    },
  ],
  quotes: [
    {
      id: "Q-2606-118",
      inquiryId: "INQ-2606-041",
      customerId: "CUS-101",
      lines: [
        {
          id: "QL-118-1",
          specId: "SPEC-240-35C",
          lengthM: 3000,
          metalRatePerKg: 248,
          overheadPerM: 820,
          marginPct: 14,
          metalCostPerM: 193,
          baseCostPerM: 1013,
          lineSubtotalInr: 3039000,
          lineMarginInr: 425460,
          lineTotalInr: 3464460,
          hsnCode: "8544",
          gstRatePct: 18,
        },
      ],
      subtotalInr: 3464460,
      gstInr: 623603,
      totalInr: 4088063,
      status: "Sent",
      validUntil: "2026-07-08",
      marginReviewRequired: false,
      createdAt: "2026-06-18",
    },
    {
      id: "Q-2606-119",
      inquiryId: "INQ-2606-042",
      customerId: "CUS-103",
      lines: [
        {
          id: "QL-119-1",
          specId: "SPEC-11KV-1C",
          lengthM: 4500,
          metalRatePerKg: 248,
          overheadPerM: 1260,
          marginPct: 9,
          metalCostPerM: 242,
          baseCostPerM: 1502,
          lineSubtotalInr: 6759000,
          lineMarginInr: 608310,
          lineTotalInr: 7367310,
          hsnCode: "8544",
          gstRatePct: 18,
        },
      ],
      subtotalInr: 7367310,
      gstInr: 1326116,
      totalInr: 8693426,
      status: "Review",
      validUntil: "2026-07-05",
      marginReviewRequired: true,
      createdAt: "2026-06-19",
    },
    {
      id: "Q-2606-120",
      customerId: "CUS-101",
      lines: [
        {
          id: "QL-120-1",
          specId: "SPEC-240-35C",
          lengthM: 2000,
          metalRatePerKg: 248,
          overheadPerM: 820,
          marginPct: 14,
          metalCostPerM: 193,
          baseCostPerM: 1013,
          lineSubtotalInr: 2026000,
          lineMarginInr: 283640,
          lineTotalInr: 2309640,
          hsnCode: "8544",
          gstRatePct: 18,
        },
      ],
      subtotalInr: 2309640,
      gstInr: 415735,
      totalInr: 2725375,
      status: "On board",
      validUntil: "2026-07-15",
      marginReviewRequired: false,
      convertedOrderId: "ORD-7743",
      createdAt: "2026-06-22",
    },
  ],
  orders: [
    {
      id: "ORD-7741",
      quoteId: "Q-2606-118",
      inquiryId: "INQ-2606-041",
      customerId: "CUS-101",
      title: "Metro feeder package 4",
      specSummary: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS",
      stage: "In Production",
      priority: "Medium",
      amountInr: 4088063,
      promisedDate: "2026-06-29",
      completionPct: 64,
      ownerRole: "Operations",
      dispatchId: "DSP-3391",
      invoiceId: "INV-2606-062",
      jobCardId: "JC-8814",
      gtpId: "GTP-001",
      // ECD 2026-06-28 → call-by 2026-06-18: overdue at the pinned "today" so the
      // inspection countdown + escalation signal are visible in the demo.
      estimatedCompletionDate: "2026-06-28",
      inspectionStatus: "Not called",
      createdAt: "2026-06-19",
    },
    {
      id: "ORD-7742",
      quoteId: "Q-2606-119",
      inquiryId: "INQ-2606-042",
      customerId: "CUS-103",
      title: "11kV utility tender lot",
      specSummary: "1C x 300 sq mm Al, screened XLPE, AWA armoured, FRLS",
      stage: "Quoted",
      priority: "High",
      amountInr: 8693426,
      promisedDate: "2026-07-10",
      completionPct: 0,
      ownerRole: "Sales",
      createdAt: "2026-06-20",
    },
    {
      // Repeat order sitting in Won with no approved GTP — demos the production
      // gate and the "GTP missing" signal.
      id: "ORD-7743",
      quoteId: "Q-2606-120",
      customerId: "CUS-101",
      title: "Metro feeder package 5 (repeat)",
      specSummary: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS",
      stage: "Won",
      priority: "Medium",
      amountInr: 2725375,
      promisedDate: "2026-07-20",
      completionPct: 20,
      ownerRole: "Operations",
      inspectionStatus: "Not called",
      createdAt: "2026-06-22",
    },
  ],
  gtps: [
    {
      id: "GTP-001",
      orderId: "ORD-7741",
      customerId: "CUS-101",
      state: "Maharashtra",
      boardName: "Shakti Infra Projects",
      specId: "SPEC-240-35C",
      cableType: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS, 1.1kV",
      format: "self-generated",
      sections: [
        { id: "gs-standard", label: "Applicable standard", value: "IS 7098-1 · 650/1100 V (1.1 kV)", source: "is-standard" },
        { id: "gs-conductor", label: "Conductor", value: "Aluminium, Class 2 compacted, 240 sq mm phase + 120 sq mm neutral", source: "is-standard" },
        { id: "gs-insulation", label: "Insulation", value: "XLPE, 90°C continuous rating", source: "is-standard" },
        { id: "gs-armour", label: "Armour", value: "GI strip (GSS) over inner sheath/bedding", source: "is-standard" },
        { id: "gs-sheath", label: "Outer sheath", value: "FRLS PVC, black", source: "is-standard" },
        { id: "gs-tests", label: "Routine tests", value: "Conductor resistance, HVT 3 kV/5 min, insulation resistance", source: "is-standard" },
        { id: "gs-marking", label: "Drum marking", value: "Consignee, drum no., designation, length, BIS/ISI mark", source: "client-fixed" },
        { id: "gs-delivery", label: "Delivery drums", value: "Steel-wood drums, 1000 m standard lengths", source: "client-fixed" },
      ],
      status: "Approved",
      signOffs: [
        { role: "Divisional Engineer", name: "S. Kulkarni", stampedAt: "2026-06-20T11:00:00+05:30" },
        { role: "Assistant Engineer", name: "P. Jadhav", stampedAt: "2026-06-20T15:30:00+05:30" },
      ],
      version: 1,
      createdAt: "2026-06-19",
      updatedAt: "2026-06-20",
    },
    // Pre-seeded public formats: instant prefill for boards we know before the
    // client hands us anything — a demo moment (kamble-meeting-improvements.md §1).
    {
      id: "GTP-TPL-WBCL",
      state: "West Bengal",
      boardName: "WBCL",
      specId: "SPEC-240-35C",
      cableType: "LT XLPE power cable, 1.1kV class",
      format: "client-fixed",
      sections: [
        { id: "gs-standard", label: "Applicable standard", value: "IS 7098-1", source: "client-fixed" },
        { id: "gs-conductor", label: "Conductor", value: "Aluminium, Class 2 compacted per IS 8130", source: "client-fixed" },
        { id: "gs-insulation", label: "Insulation", value: "XLPE per IS 7098-1 Table 1", source: "client-fixed" },
        { id: "gs-armour", label: "Armour", value: "GI strip per IS 3975", source: "client-fixed" },
        { id: "gs-sheath", label: "Outer sheath", value: "FRLS PVC ST2", source: "client-fixed" },
        { id: "gs-tests", label: "Acceptance tests", value: "Per IS 7098-1 clause 15, witnessed by board inspector", source: "client-fixed" },
        { id: "gs-marking", label: "Drum marking", value: "WBCL PO no., drum no., designation, length, ISI mark", source: "client-fixed" },
      ],
      status: "Approved",
      signOffs: [],
      version: 1,
      isTemplate: true,
      createdAt: "2026-06-15",
      updatedAt: "2026-06-15",
    },
    {
      id: "GTP-TPL-MSEDCL",
      state: "Maharashtra",
      boardName: "MSEDCL",
      specId: "SPEC-11KV-1C",
      cableType: "HT XLPE cable, 11kV class",
      format: "client-fixed",
      sections: [
        { id: "gs-standard", label: "Applicable standard", value: "IS 7098-2", source: "client-fixed" },
        { id: "gs-conductor", label: "Conductor", value: "Aluminium, Class 2 compacted, screened", source: "client-fixed" },
        { id: "gs-insulation", label: "Insulation", value: "XLPE with semi-conducting screens", source: "client-fixed" },
        { id: "gs-armour", label: "Armour", value: "Aluminium round wire (AWA) for single core", source: "client-fixed" },
        { id: "gs-sheath", label: "Outer sheath", value: "FRLS PVC", source: "client-fixed" },
        { id: "gs-tests", label: "Acceptance tests", value: "Partial discharge + HVT per IS 7098-2, witnessed", source: "client-fixed" },
        { id: "gs-marking", label: "Drum marking", value: "MSEDCL PO no., drum no., designation, length, ISI mark", source: "client-fixed" },
      ],
      status: "Approved",
      signOffs: [],
      version: 1,
      isTemplate: true,
      createdAt: "2026-06-15",
      updatedAt: "2026-06-15",
    },
  ],
  rawMaterialChecks: [
    {
      id: "RMC-001",
      orderId: "ORD-7741",
      materialType: "Aluminium rod (EC grade) + XLPE compound + GI strip",
      checks: [
        { id: "rm-visual", label: "Visual check", result: "Pass" },
        { id: "rm-dimension", label: "Dimension check", result: "Pass" },
        { id: "rm-smoothness", label: "Surface smoothness", result: "Pass" },
        { id: "rm-electrical", label: "Electrical test (conductivity)", result: "Pass" },
        { id: "rm-mechanical", label: "Mechanical test (tensile/elongation)", result: "Pass" },
      ],
      passedAt: "2026-06-20T10:00:00+05:30",
      approvedBy: "Meera Ops",
    },
  ],
  finishedCableQc: [
    {
      id: "FQC-001",
      orderId: "ORD-7741",
      drumNo: "DR-7741-A",
      hvtResult: "Pass",
      resistanceMeasuredOhmPerKm: 0.123,
      resistanceSpecMaxOhmPerKm: 0.125,
      irValueMohmKm: 5200,
      result: "Pass",
      certRef: "TC-7741-A",
      testedAt: "2026-06-22T14:00:00+05:30",
    },
    {
      id: "FQC-002",
      orderId: "ORD-7741",
      drumNo: "DR-7741-B",
      hvtResult: "Pending",
      resistanceSpecMaxOhmPerKm: 0.125,
      result: "Pending",
    },
  ],
  machineIncidents: [
    {
      id: "MI-001",
      orderId: "ORD-7741",
      jobCardId: "JC-8814",
      machineType: "Extruder",
      failureMode: "Heater zone temperature drift",
      description: "Zone 3 overshooting set point by 12°C on the 240 sq mm run; sheath surface showing roughness.",
      proposedFix: "Swap zone 3 thermocouple and recalibrate before restarting the run.",
      status: "Awaiting approval",
      reportedAt: "2026-06-23T08:15:00+05:30",
    },
  ],
  inspectionReports: [],
  jobCards: [
    {
      id: "JC-8814",
      orderId: "ORD-7741",
      specId: "SPEC-240-35C",
      conductorDetail: "Aluminium Class 2 compacted, 240 sq mm phase + 120 sq mm neutral",
      insulationDetail: "XLPE extrusion, 90C rating",
      armourDetail: "GI strip armouring over bedding",
      sheathDetail: "FRLS PVC black outer sheath",
      drumPlan: [
        {
          drumNo: "DR-7741-A",
          drumType: "Steel-Wood",
          lengthM: 1000,
          grossWeightKg: 3820,
          markings: "ORD-7741 / 3.5C x 240 Al XLPE FRLS / 1000m",
        },
        {
          drumNo: "DR-7741-B",
          drumType: "Steel-Wood",
          lengthM: 1000,
          grossWeightKg: 3820,
          markings: "ORD-7741 / 3.5C x 240 Al XLPE FRLS / 1000m",
        },
      ],
      operatorNotes: "Armour lay checked; third drum scheduled after conductor QA.",
      qualityChecks: [
        { id: "QC-1", label: "Conductor resistance", result: "Pass" },
        { id: "QC-2", label: "Spark/HV test", result: "Pending" },
        { id: "QC-3", label: "Print legibility", result: "Pass" },
      ],
      updatedAt: "2026-06-23",
    },
  ],
  dispatches: [
    {
      id: "DSP-3391",
      orderId: "ORD-7741",
      transporter: "BlueLine Logistics",
      vehicleNo: "MH12 AB 4412",
      ewayBillRequired: true,
      checklist: [
        { id: "marking", label: "Drum markings stencilled", done: true, required: true },
        { id: "marking-verified", label: "Drum marking matches GTP", done: false, required: true },
        // Only auto-ticks once every drum has a verified test certificate.
        { id: "test", label: "Test certificates attached (all drums)", done: false, required: true },
        { id: "clearance", label: "Inspection clearance (DI received)", done: false, required: true },
        { id: "packing", label: "Packing list ready", done: false, required: true },
        { id: "invoice", label: "Invoice ready", done: false, required: true },
        { id: "eway", label: "E-way bill generated", done: false, required: true },
      ],
      drumTestCerts: [{ drumNo: "DR-7741-A", certRef: "TC-7741-A", verified: true }],
      createdAt: "2026-06-21",
    },
  ],
  invoices: [
    {
      id: "INV-2606-062",
      kind: "Draft",
      orderId: "ORD-7741",
      customerId: "CUS-101",
      taxableInr: 3464460,
      cgstInr: 311801,
      sgstInr: 311802,
      totalInr: 4088063,
      hsnCode: "8544",
      status: "Blocked",
      syncStatus: "Missing dispatch data",
      risk: "Medium",
      dueDate: "2026-07-29",
      createdAt: "2026-06-19",
    },
  ],
  compliance: [
    {
      id: "CMP-501",
      type: "EMD",
      customerId: "CUS-103",
      inquiryId: "INQ-2606-042",
      amountInr: 250000,
      dueDate: "2026-06-24",
      status: "Needs approval",
      risk: "High",
      createdAt: "2026-06-20",
    },
    {
      id: "CMP-502",
      type: "Bank guarantee",
      customerId: "CUS-101",
      inquiryId: "INQ-2606-041",
      amountInr: 500000,
      dueDate: "2026-07-02",
      status: "Draft requested",
      risk: "Medium",
      instrumentRef: "BG-DRAFT-118",
      createdAt: "2026-06-18",
    },
  ],
  activity: [
    {
      id: "ACT-001",
      at: "2026-06-23T09:00:00+05:30",
      actorRole: "Sales",
      actorName: "Ravi Sales",
      type: "quote.sent",
      recordType: "quote",
      recordId: "Q-2606-118",
      text: "Quote Q-2606-118 sent to Shakti Infra Projects.",
    },
    {
      id: "ACT-002",
      at: "2026-06-23T10:00:00+05:30",
      actorRole: "Operations",
      actorName: "Meera Ops",
      type: "jobcard.updated",
      recordType: "jobcard",
      recordId: "JC-8814",
      text: "Job card JC-8814 updated with drum plan and QA checks.",
    },
    {
      id: "ACT-003",
      at: "2026-06-20T15:30:00+05:30",
      actorRole: "Operations",
      actorName: "Meera Ops",
      type: "gtp.approved",
      recordType: "gtp",
      recordId: "GTP-001",
      text: "GTP-001 approved — divisional engineer and AE stamps recorded. Production unblocked for ORD-7741.",
    },
    {
      id: "ACT-004",
      at: "2026-06-23T08:15:00+05:30",
      actorRole: "Operations",
      actorName: "Meera Ops",
      type: "incident.logged",
      recordType: "incident",
      recordId: "MI-001",
      text: "Machine incident MI-001 logged on Extruder — production hold pending Owner approval.",
    },
  ],
  signals: [
    {
      id: "SIG-001",
      type: "Missing document",
      severity: "High",
      route: "/dispatch?orderId=ORD-7741",
      recordId: "DSP-3391",
      text: "Packing list and e-way bill are pending for ORD-7741.",
    },
    {
      id: "SIG-002",
      type: "Margin anomaly",
      severity: "High",
      route: "/quote?quoteId=Q-2606-119",
      recordId: "Q-2606-119",
      text: "Quote Q-2606-119 has 9% margin and needs owner review.",
    },
  ],
  approvals: [
    {
      id: "APR-001",
      kind: "Margin approval",
      recordType: "quote",
      recordId: "Q-2606-119",
      requestedByRole: "Sales",
      status: "Pending",
      reason: "Quote margin is below the 12% policy threshold.",
      createdAt: "2026-06-20",
    },
    {
      id: "APR-002",
      kind: "BG/EMD approval",
      recordType: "compliance",
      recordId: "CMP-501",
      requestedByRole: "Sales",
      status: "Pending",
      reason: "EMD approval required before tender submission.",
      createdAt: "2026-06-20",
    },
    {
      id: "APR-003",
      kind: "Machine incident",
      recordType: "incident",
      recordId: "MI-001",
      requestedByRole: "Operations",
      status: "Pending",
      reason:
        "Extruder zone 3 temperature drift on ORD-7741 — production held; fix: swap thermocouple and recalibrate.",
      createdAt: "2026-06-23",
    },
  ],
  integrations: [
    {
      id: "zoho-books",
      name: "Zoho Books",
      category: "Accounting",
      direction: "out",
      status: "Connected",
      lastSyncAt: "2026-06-22T16:15:00+05:30",
      config: { organizationId: "****9012" },
      health: { ok: true, message: "Ready to sync invoices" },
    },
    {
      id: "crm",
      name: "CRM",
      category: "CRM",
      direction: "bidirectional",
      status: "Connected",
      lastSyncAt: "2026-06-22T11:00:00+05:30",
      config: { endpoint: "crm.autoloom.example" },
      health: { ok: true, message: "Customer import healthy" },
    },
    {
      id: "eway-bill",
      name: "E-way Bill",
      category: "Compliance",
      direction: "out",
      status: "Connected",
      lastSyncAt: "2026-06-21T18:10:00+05:30",
      config: { gstin: "27*********1ZV" },
      health: { ok: true, message: "Sandbox generator enabled" },
    },
    {
      id: "mcx-index",
      name: "MCX Metal Index",
      category: "Pricing",
      direction: "in",
      status: "Connected",
      lastSyncAt: "2026-06-23T08:30:00+05:30",
      config: { mode: "mock drift" },
      health: { ok: true, message: "Al ₹248/kg · Cu ₹886/kg" },
    },
  ],
  syncLogs: [
    {
      id: "SYN-001",
      connectorId: "mcx-index",
      at: "2026-06-23T08:30:00+05:30",
      action: "pull",
      status: "success",
      message: "Fetched pinned MCX mock rates.",
    },
  ],
};
