//  Main initial CableStore dataset containing demo customers,
// inquiries, quotes, orders, materials, etc.

import type { CableStore } from "@/lib/services/types";

export const seedData: CableStore = {
  org: {
    companyName: "Autoloom Cables Pvt. Ltd.",
    gstin: "27AAHCA2600A1ZV",
    homeStateCode: "27",
    address: "MIDC Industrial Area, Pune, Maharashtra",
    timezone: "Asia/Kolkata",
  },
  policies: {
    marginThresholdPct: 12,
    ewayThresholdInr: 50000,
    gstRatePct: 18,
    creditLimitEnforced: true,
    dispatchHoldMode: "soft",
  },
  users: [
    { id: "USR-001", name: "Asha Owner", email: "owner@autoloom.test", role: "Owner", active: true },
    { id: "USR-002", name: "Ravi Sales", email: "sales@autoloom.test", role: "Sales", active: true },
    { id: "USR-003", name: "Meera Ops", email: "ops@autoloom.test", role: "Operations", active: true },
    { id: "USR-004", name: "Kabir Accounts", email: "accounts@autoloom.test", role: "Accounts", active: true },
  ],
  materials: [
    // Conductors — auto-refreshed from the MCX metal index.
    { id: "MAT-AL", name: "Aluminium (EC grade)", category: "Conductor", ratePerKg: 248, source: "MCX", matchMaterial: "Aluminium", updatedAt: "2026-06-23T08:30:00+05:30" },
    { id: "MAT-CU", name: "Copper (ETP grade)", category: "Conductor", ratePerKg: 886, source: "MCX", matchMaterial: "Copper", updatedAt: "2026-06-23T08:30:00+05:30" },
    // Insulation compounds — manual.
    { id: "MAT-XLPE", name: "XLPE compound", category: "Insulation", ratePerKg: 165, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-PVC-INS", name: "PVC insulation compound", category: "Insulation", ratePerKg: 120, source: "Manual", updatedAt: "2026-06-20" },
    // Armour — manual.
    { id: "MAT-GI", name: "GI strip / wire (armour)", category: "Armour", ratePerKg: 95, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-AL-ARMOUR", name: "Aluminium armour wire", category: "Armour", ratePerKg: 252, source: "Manual", updatedAt: "2026-06-20" },
    // Sheath — manual.
    { id: "MAT-PVC-SH", name: "PVC sheath compound", category: "Sheath", ratePerKg: 110, source: "Manual", updatedAt: "2026-06-20" },
    { id: "MAT-LSZH", name: "Zero-halogen (LSZH) sheath", category: "Sheath", ratePerKg: 240, source: "Manual", updatedAt: "2026-06-20" },
  ],
  specs: [
    {
      id: "SPEC-240-35C",
      standard: "IS 7098-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "3.5C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 240,
      neutralSizeSqMm: 120,
      insulation: "XLPE",
      armour: "GI strip (GSS)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      designation: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS, 1.1kV",
      cableCode: "A2XFY",
      approxOuterDiaMm: 58,
      approxWeightKgPerKm: 3520,
      bisLicenceNo: "CM/L-7200123456",
      rohsCompliant: true,
    },
    {
      id: "SPEC-185-4C",
      standard: "IS 1554-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "4C",
      conductorMaterial: "Copper",
      conductorClass: "Class 2 (stranded)",
      conductorSizeSqMm: 185,
      insulation: "PVC (Type C)",
      armour: "GI round wire (GSW)",
      sheath: "PVC (ST2)",
      flameClass: "FR",
      designation: "4C x 185 sq mm Cu, HR PVC, GI round wire armoured, 1.1kV",
      cableCode: "YWY",
      approxOuterDiaMm: 54,
      approxWeightKgPerKm: 6920,
      rohsCompliant: true,
    },
    {
      id: "SPEC-11KV-1C",
      standard: "IS 7098-2",
      voltageGrade: "6.35/11 kV",
      cores: "1C",
      conductorMaterial: "Aluminium",
      conductorClass: "Class 2 compacted",
      conductorSizeSqMm: 300,
      insulation: "XLPE",
      armour: "Aluminium wire (AWA)",
      sheath: "FRLS PVC",
      flameClass: "FRLS",
      screened: true,
      designation: "1C x 300 sq mm Al, screened XLPE, AWA armoured, FRLS, 11kV",
      cableCode: "A2XWAY",
      approxOuterDiaMm: 44,
      approxWeightKgPerKm: 2480,
      bisLicenceNo: "CM/L-7200456789",
      rohsCompliant: true,
    },
    {
      id: "SPEC-SOLAR-16",
      standard: "IEC 60502-1",
      voltageGrade: "650/1100 V (1.1 kV)",
      cores: "1C",
      conductorMaterial: "Copper",
      conductorClass: "Class 5 (flexible)",
      conductorSizeSqMm: 16,
      insulation: "XLPO (solar/UV)",
      armour: "Unarmoured",
      sheath: "Zero-halogen (ZHFR/LSZH)",
      flameClass: "LSZH",
      designation: "1C x 16 sq mm Cu flexible solar DC cable, XLPO, LSZH",
      cableCode: "PV1-F",
      approxOuterDiaMm: 9,
      approxWeightKgPerKm: 190,
      rohsCompliant: true,
    },
  ],
  customers: [
    {
      id: "CUS-101",
      name: "Shakti Infra Projects",
      segment: "EPC contractor",
      contactName: "Nitin Rao",
      phone: "+91 98765 11001",
      email: "procurement@shaktiinfra.test",
      billingAddress: "Andheri East, Mumbai",
      shippingAddress: "Metro Package 4, Thane",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400069",
      gstin: "27AABCS1234F1Z5",
      stateCode: "27",
      paymentTerms: "30 days from invoice",
      creditLimitInr: 12000000,
      creditUsedInr: 7800000,
      crmId: "CRM-001",
      createdAt: "2026-06-01",
    },
    {
      id: "CUS-102",
      name: "Dakshin Solar EPC",
      segment: "Solar installer",
      contactName: "Priya Menon",
      phone: "+91 98765 11002",
      email: "buy@dakshinsolar.test",
      billingAddress: "Peenya Industrial Area, Bengaluru",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560058",
      gstin: "29AAECD4567H1ZX",
      stateCode: "29",
      paymentTerms: "50% advance, balance before dispatch",
      creditLimitInr: 4500000,
      creditUsedInr: 4200000,
      msmeRegistered: true,
      crmId: "CRM-002",
      createdAt: "2026-06-03",
    },
    {
      id: "CUS-103",
      name: "Narmada Utilities Board",
      segment: "Government/PSU",
      contactName: "Arvind Shah",
      phone: "+91 98765 11003",
      email: "tender@narmadautilities.test",
      billingAddress: "Race Course Road, Vadodara",
      city: "Vadodara",
      state: "Gujarat",
      pincode: "390007",
      gstin: "24AAALN9999C1Z8",
      stateCode: "24",
      paymentTerms: "45 days, BG required",
      creditLimitInr: 22000000,
      creditUsedInr: 3000000,
      createdAt: "2026-06-05",
    },
    {
      id: "CUS-104",
      name: "Vector OEM Drives",
      segment: "OEM",
      contactName: "Farah Khan",
      phone: "+91 98765 11004",
      email: "purchase@vectoroem.test",
      billingAddress: "Chakan MIDC, Pune",
      city: "Pune",
      state: "Maharashtra",
      pincode: "410501",
      gstin: "27AAACV8080D1ZM",
      stateCode: "27",
      paymentTerms: "15 days from invoice",
      creditLimitInr: 3000000,
      creditUsedInr: 900000,
      createdAt: "2026-06-08",
    },
  ],
  inquiries: [
    {
      id: "INQ-2606-041",
      customerId: "CUS-101",
      requirement: "Metro feeder cable for package 4",
      specId: "SPEC-240-35C",
      source: "Repeat order",
      estimatedValueInr: 8650000,
      stage: "Quote sent",
      ownerRole: "Sales",
      nextAction: "Confirm final delivery split",
      followUpDate: "2026-06-23",
      createdAt: "2026-06-12",
    },
    {
      id: "INQ-2606-042",
      customerId: "CUS-103",
      requirement: "11kV screened cable tender",
      specId: "SPEC-11KV-1C",
      source: "Tender portal",
      tenderRef: "NUB/11KV/2026/118",
      estimatedValueInr: 14800000,
      stage: "Quoting",
      ownerRole: "Sales",
      nextAction: "Owner approval for EMD and margin",
      followUpDate: "2026-06-24",
      createdAt: "2026-06-15",
    },
    {
      id: "INQ-2606-043",
      customerId: "CUS-102",
      requirement: "Solar DC cable for 12 MW site",
      specId: "SPEC-SOLAR-16",
      source: "Website",
      estimatedValueInr: 2850000,
      stage: "New",
      ownerRole: "Sales",
      nextAction: "Capture drum schedule",
      followUpDate: "2026-06-25",
      createdAt: "2026-06-20",
    },
  ],
  quotes: [
    {
      id: "Q-2606-118",
      inquiryId: "INQ-2606-041",
      customerId: "CUS-101",
      lines: [
        {
          id: "QL-118-1",
          specId: "SPEC-240-35C",
          lengthM: 3000,
          metalRatePerKg: 248,
          overheadPerM: 820,
          marginPct: 14,
          metalCostPerM: 193,
          baseCostPerM: 1013,
          lineSubtotalInr: 3039000,
          lineMarginInr: 425460,
          lineTotalInr: 3464460,
          hsnCode: "8544",
          gstRatePct: 18,
        },
      ],
      subtotalInr: 3464460,
      gstInr: 623603,
      totalInr: 4088063,
      status: "Sent",
      validUntil: "2026-07-08",
      marginReviewRequired: false,
      createdAt: "2026-06-18",
    },
    {
      id: "Q-2606-119",
      inquiryId: "INQ-2606-042",
      customerId: "CUS-103",
      lines: [
        {
          id: "QL-119-1",
          specId: "SPEC-11KV-1C",
          lengthM: 4500,
          metalRatePerKg: 248,
          overheadPerM: 1260,
          marginPct: 9,
          metalCostPerM: 242,
          baseCostPerM: 1502,
          lineSubtotalInr: 6759000,
          lineMarginInr: 608310,
          lineTotalInr: 7367310,
          hsnCode: "8544",
          gstRatePct: 18,
        },
      ],
      subtotalInr: 7367310,
      gstInr: 1326116,
      totalInr: 8693426,
      status: "Review",
      validUntil: "2026-07-05",
      marginReviewRequired: true,
      createdAt: "2026-06-19",
    },
  ],
  orders: [
    {
      id: "ORD-7741",
      quoteId: "Q-2606-118",
      inquiryId: "INQ-2606-041",
      customerId: "CUS-101",
      title: "Metro feeder package 4",
      specSummary: "3.5C x 240 sq mm Al, XLPE, GI strip armoured, FRLS",
      stage: "In Production",
      priority: "Medium",
      amountInr: 4088063,
      promisedDate: "2026-06-29",
      completionPct: 64,
      ownerRole: "Operations",
      dispatchId: "DSP-3391",
      invoiceId: "INV-2606-062",
      jobCardId: "JC-8814",
      createdAt: "2026-06-19",
    },
    {
      id: "ORD-7742",
      quoteId: "Q-2606-119",
      inquiryId: "INQ-2606-042",
      customerId: "CUS-103",
      title: "11kV utility tender lot",
      specSummary: "1C x 300 sq mm Al, screened XLPE, AWA armoured, FRLS",
      stage: "Quoted",
      priority: "High",
      amountInr: 8693426,
      promisedDate: "2026-07-10",
      completionPct: 0,
      ownerRole: "Sales",
      createdAt: "2026-06-20",
    },
  ],
  jobCards: [
    {
      id: "JC-8814",
      orderId: "ORD-7741",
      specId: "SPEC-240-35C",
      conductorDetail: "Aluminium Class 2 compacted, 240 sq mm phase + 120 sq mm neutral",
      insulationDetail: "XLPE extrusion, 90C rating",
      armourDetail: "GI strip armouring over bedding",
      sheathDetail: "FRLS PVC black outer sheath",
      drumPlan: [
        {
          drumNo: "DR-7741-A",
          drumType: "Steel-Wood",
          lengthM: 1000,
          grossWeightKg: 3820,
          markings: "ORD-7741 / 3.5C x 240 Al XLPE FRLS / 1000m",
        },
        {
          drumNo: "DR-7741-B",
          drumType: "Steel-Wood",
          lengthM: 1000,
          grossWeightKg: 3820,
          markings: "ORD-7741 / 3.5C x 240 Al XLPE FRLS / 1000m",
        },
      ],
      operatorNotes: "Armour lay checked; third drum scheduled after conductor QA.",
      qualityChecks: [
        { id: "QC-1", label: "Conductor resistance", result: "Pass" },
        { id: "QC-2", label: "Spark/HV test", result: "Pending" },
        { id: "QC-3", label: "Print legibility", result: "Pass" },
      ],
      updatedAt: "2026-06-23",
    },
  ],
  dispatches: [
    {
      id: "DSP-3391",
      orderId: "ORD-7741",
      transporter: "BlueLine Logistics",
      vehicleNo: "MH12 AB 4412",
      ewayBillRequired: true,
      checklist: [
        { id: "marking", label: "Drum markings verified", done: true, required: true },
        { id: "test", label: "Test certificate attached", done: true, required: true },
        { id: "packing", label: "Packing list ready", done: false, required: true },
        { id: "invoice", label: "Invoice ready", done: false, required: true },
        { id: "eway", label: "E-way bill generated", done: false, required: true },
      ],
      testCertificateRef: "TC-7741-A/B",
      createdAt: "2026-06-21",
    },
  ],
  invoices: [
    {
      id: "INV-2606-062",
      kind: "Draft",
      orderId: "ORD-7741",
      customerId: "CUS-101",
      taxableInr: 3464460,
      cgstInr: 311801,
      sgstInr: 311802,
      totalInr: 4088063,
      hsnCode: "8544",
      status: "Blocked",
      syncStatus: "Missing dispatch data",
      risk: "Medium",
      dueDate: "2026-07-29",
      createdAt: "2026-06-19",
    },
  ],
  compliance: [
    {
      id: "CMP-501",
      type: "EMD",
      customerId: "CUS-103",
      inquiryId: "INQ-2606-042",
      amountInr: 250000,
      dueDate: "2026-06-24",
      status: "Needs approval",
      risk: "High",
      createdAt: "2026-06-20",
    },
    {
      id: "CMP-502",
      type: "Bank guarantee",
      customerId: "CUS-101",
      inquiryId: "INQ-2606-041",
      amountInr: 500000,
      dueDate: "2026-07-02",
      status: "Draft requested",
      risk: "Medium",
      instrumentRef: "BG-DRAFT-118",
      createdAt: "2026-06-18",
    },
  ],
  activity: [
    {
      id: "ACT-001",
      at: "2026-06-23T09:00:00+05:30",
      actorRole: "Sales",
      actorName: "Ravi Sales",
      type: "quote.sent",
      recordType: "quote",
      recordId: "Q-2606-118",
      text: "Quote Q-2606-118 sent to Shakti Infra Projects.",
    },
    {
      id: "ACT-002",
      at: "2026-06-23T10:00:00+05:30",
      actorRole: "Operations",
      actorName: "Meera Ops",
      type: "jobcard.updated",
      recordType: "jobcard",
      recordId: "JC-8814",
      text: "Job card JC-8814 updated with drum plan and QA checks.",
    },
  ],
  signals: [
    {
      id: "SIG-001",
      type: "Missing document",
      severity: "High",
      route: "/dispatch?orderId=ORD-7741",
      recordId: "DSP-3391",
      text: "Packing list and e-way bill are pending for ORD-7741.",
    },
    {
      id: "SIG-002",
      type: "Margin anomaly",
      severity: "High",
      route: "/quote?quoteId=Q-2606-119",
      recordId: "Q-2606-119",
      text: "Quote Q-2606-119 has 9% margin and needs owner review.",
    },
  ],
  approvals: [
    {
      id: "APR-001",
      kind: "Margin approval",
      recordType: "quote",
      recordId: "Q-2606-119",
      requestedByRole: "Sales",
      status: "Pending",
      reason: "Quote margin is below the 12% policy threshold.",
      createdAt: "2026-06-20",
    },
    {
      id: "APR-002",
      kind: "BG/EMD approval",
      recordType: "compliance",
      recordId: "CMP-501",
      requestedByRole: "Sales",
      status: "Pending",
      reason: "EMD approval required before tender submission.",
      createdAt: "2026-06-20",
    },
  ],
  integrations: [
    {
      id: "zoho-books",
      name: "Zoho Books",
      category: "Accounting",
      direction: "out",
      status: "Connected",
      lastSyncAt: "2026-06-22T16:15:00+05:30",
      config: { organizationId: "****9012" },
      health: { ok: true, message: "Ready to sync invoices" },
    },
    {
      id: "crm",
      name: "CRM",
      category: "CRM",
      direction: "bidirectional",
      status: "Connected",
      lastSyncAt: "2026-06-22T11:00:00+05:30",
      config: { endpoint: "crm.autoloom.example" },
      health: { ok: true, message: "Customer import healthy" },
    },
    {
      id: "eway-bill",
      name: "E-way Bill",
      category: "Compliance",
      direction: "out",
      status: "Connected",
      lastSyncAt: "2026-06-21T18:10:00+05:30",
      config: { gstin: "27*********1ZV" },
      health: { ok: true, message: "Sandbox generator enabled" },
    },
    {
      id: "mcx-index",
      name: "MCX Metal Index",
      category: "Pricing",
      direction: "in",
      status: "Connected",
      lastSyncAt: "2026-06-23T08:30:00+05:30",
      config: { mode: "mock drift" },
      health: { ok: true, message: "Al ₹248/kg · Cu ₹886/kg" },
    },
  ],
  syncLogs: [
    {
      id: "SYN-001",
      connectorId: "mcx-index",
      at: "2026-06-23T08:30:00+05:30",
      action: "pull",
      status: "success",
      message: "Fetched pinned MCX mock rates.",
    },
  ],
};
